services:
  redis:
    image: redis:alpine3.19

  celery_app:
    build: 
      context: "./djangoCelery"
    container_name: djangoCeleryContainer
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./djangoCelery:/usr/src/app/
    image: celery_app:1.0
    environment:
      - DEBUG=1
      - SECRET_KEY="${SECRET_KEY}"
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - redis

  celery:
    container_name: celery
    build: 
      context: ./djangoCelery
    command: celery -A dcelery worker -l INFO
    volumes:
      - ./djangoCelery:/usr/src/app/
    ports:
      - 8001:8000
    environment:
      - DEBUG=1
      - SECRET_KEY="${SECRET_KEY}"
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - redis
  