# Generated by Django 5.0.6 on 2024-06-30 22:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='businessinfo',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='businessinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='authuser',
            name='verified_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='authuser',
            name='verified_phone_number',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='If your account is of a business type i.e. seller, then please drop your business name instead', max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='First name')),
                ('last_name', models.CharField(blank=None, help_text='Not required for business account', max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Last name')),
                ('google_id', models.CharField(max_length=256, null=True, unique=True)),
                ('github_id', models.CharField(max_length=256, null=True, unique=True)),
                ('twitter_id', models.CharField(max_length=256, null=True, unique=True)),
                ('year_of_birth', models.PositiveIntegerField()),
                ('profile_image', models.ImageField(blank=True, default='user-svgrepo-com.svg', null=True, upload_to='media/profile')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('middle_name', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('first_name', 'last_name', 'middle_name')},
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state_province_region', models.CharField(max_length=150)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('address_type', models.CharField(blank=True, choices=[('billing', 'Billing'), ('shipping', 'Shipping')], max_length=50, null=True)),
                ('buyer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_address', to='auths.buyer')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='If your account is of a business type i.e. seller, then please drop your business name instead', max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='First name')),
                ('last_name', models.CharField(blank=None, help_text='Not required for business account', max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Last name')),
                ('google_id', models.CharField(max_length=256, null=True, unique=True)),
                ('github_id', models.CharField(max_length=256, null=True, unique=True)),
                ('twitter_id', models.CharField(max_length=256, null=True, unique=True)),
                ('year_of_birth', models.PositiveIntegerField()),
                ('profile_image', models.ImageField(blank=True, default='user-svgrepo-com.svg', null=True, upload_to='media/profile')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('business_name', models.CharField(error_messages='Business Name already exists', max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Business Name')),
                ('business_started_since', models.DateField(blank=True, help_text='(If applicable)', null=True)),
                ('business_type', models.CharField(choices=[('SP', 'Proprietorship'), ('C', 'Corporation'), ('P', 'Partnership'), ('LLC', 'Limited liability company')], default='SP', max_length=3)),
                ('business_description', models.CharField(blank=True, max_length=800, null=True)),
                ('business_custom_care_phone_number', models.CharField(max_length=15, unique=True)),
                ('registration_number', models.CharField(blank=True, help_text='(If applicable)', max_length=50, null=True, unique=True)),
                ('tax_identification_number', models.CharField(blank=True, help_text='(If applicable)', max_length=50, null=True, unique=True)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('website', models.URLField(blank=True, help_text='(If applicable)', null=True, unique=True)),
                ('business_social_A', models.URLField(blank=True, help_text='(If applicable)', null=True)),
                ('business_social_B', models.URLField(blank=True, help_text='(If applicable)', null=True)),
                ('business_social_C', models.URLField(blank=True, help_text='(If applicable)', null=True)),
                ('business_social_D', models.URLField(blank=True, help_text='(If applicable)', null=True)),
                ('business_confirmation', models.BooleanField(default=False)),
                ('created_on', models.DateField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'unique_together': {('first_name', 'last_name')},
            },
        ),
        migrations.AlterField(
            model_name='businessfeedback',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_feedback', to='auths.seller'),
        ),
        migrations.CreateModel(
            name='SellerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state_province_region', models.CharField(max_length=150)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('address_type', models.CharField(blank=True, choices=[('billing', 'Billing'), ('shipping', 'Shipping')], max_length=50, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_address', to='auths.seller')),
            ],
        ),
        migrations.DeleteModel(
            name='PersonalInfo',
        ),
        migrations.DeleteModel(
            name='BusinessInfo',
        ),
    ]
