# Generated by Django 5.0.6 on 2024-06-22 17:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0004_authuser_is_active_authuser_is_staff'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='authuser',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='authuser',
            name='account_type',
            field=models.CharField(choices=[('b', 'Buyer'), ('s', 'Seller'), ('bt', 'Both')], default='b', max_length=2),
        ),
        migrations.AddField(
            model_name='authuser',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='authuser',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='email',
            field=models.EmailField(help_text='If your account is of a business type i.e. seller, then please drop your business email instead', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='phoneNumber',
            field=models.CharField(help_text='Email. If your account is of a business type i.e. seller, please drop your business phone number instead', max_length=15, unique=True, verbose_name='Phone number'),
        ),
        migrations.CreateModel(
            name='BusinessInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='If your account is of a business type i.e. seller, then please drop your business name instead', max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='First name')),
                ('last_name', models.CharField(blank=None, help_text='Not required for business account', max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Last name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('business_name', models.CharField(error_messages='Business Name already exists', max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Business Name')),
                ('business_location', models.CharField(max_length=150)),
                ('business_country', models.CharField(max_length=20)),
                ('business_started_since', models.DateField(blank=True, help_text='(If Applicable)', null=True)),
                ('business_type', models.CharField(choices=[('SP', 'Proprietorship'), ('C', 'Corporation'), ('P', 'Partnership'), ('LLC', 'Limited liability company')], default='SP', max_length=3)),
                ('business_description', models.CharField(blank=True, max_length=300)),
                ('business_custom_care_phone_number', models.CharField(max_length=15, unique=True)),
                ('registration_number', models.CharField(blank=True, help_text='(If Applicable)', max_length=50, unique=True)),
                ('tax_identification_number', models.CharField(blank=True, help_text='(If Applicable)', max_length=50, unique=True)),
                ('website', models.URLField(blank=True, help_text='(If Applicable)', unique=True)),
                ('business_social_A', models.URLField(blank=True, help_text='(If Applicable)')),
                ('business_social_B', models.URLField(blank=True, help_text='(If Applicable)')),
                ('business_social_C', models.URLField(blank=True, help_text='(If Applicable)')),
                ('business_social_D', models.URLField(blank=True, help_text='(If Applicable)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'unique_together': {('first_name', 'last_name')},
            },
        ),
        migrations.CreateModel(
            name='BusinessFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_rating', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1)),
                ('feedback_has_verified_purchase', models.BooleanField(default=False)),
                ('feedback_comment', models.TextField()),
                ('feedback_is_valid', models.BooleanField(default=True)),
                ('feedback_from', models.ManyToManyField(related_name='business_from', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_feedback', to='auths.businessinfo')),
            ],
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='user_type',
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='If your account is of a business type i.e. seller, then please drop your business name instead', max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='First name')),
                ('last_name', models.CharField(blank=None, help_text='Not required for business account', max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Last name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('country', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'unique_together': {('first_name', 'last_name')},
            },
        ),
    ]
