# Generated by Django 5.0.6 on 2024-07-01 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0005_alter_authuser_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='year_of_birth',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='year_of_birth',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
