# Generated by Django 5.0.6 on 2024-06-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0005_alter_authuser_unique_together_authuser_account_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='profile_image',
            field=models.ImageField(blank=True, default='user-svgrepo-com.svg', null=True, upload_to='media/profile'),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='profile_image',
            field=models.ImageField(blank=True, default='user-svgrepo-com.svg', null=True, upload_to='media/profile'),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='business_social_A',
            field=models.URLField(blank=True, help_text='(If applicable)'),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='business_social_B',
            field=models.URLField(blank=True, help_text='(If applicable)'),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='business_social_C',
            field=models.URLField(blank=True, help_text='(If applicable)'),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='business_social_D',
            field=models.URLField(blank=True, help_text='(If applicable)'),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='business_started_since',
            field=models.DateField(blank=True, help_text='(If applicable)', null=True),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='registration_number',
            field=models.CharField(blank=True, help_text='(If applicable)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='tax_identification_number',
            field=models.CharField(blank=True, help_text='(If applicable)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='website',
            field=models.URLField(blank=True, help_text='(If applicable)', unique=True),
        ),
    ]
