# Generated by Django 5.0.6 on 2024-07-02 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0006_alter_buyer_year_of_birth_alter_seller_year_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authuser',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
    ]
