# Generated by Django 5.0.6 on 2024-07-04 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0007_rename_phonenumber_authuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='first_name',
            field=models.CharField(help_text='If your account is of a business type i.e. seller, then please drop your business name instead', max_length=30, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='last_name',
            field=models.CharField(blank=None, help_text='Not required for business account', max_length=30, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='first_name',
            field=models.CharField(help_text='If your account is of a business type i.e. seller, then please drop your business name instead', max_length=30, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='last_name',
            field=models.CharField(blank=None, help_text='Not required for business account', max_length=30, verbose_name='Last name'),
        ),
    ]
